# Generated by Django 4.2.1 on 2023-07-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyventojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butas',
            name='flat_nr',
            field=models.IntegerField(verbose_name='Buto numeris'),
        ),
        migrations.AlterField(
            model_name='butas',
            name='size_kv',
            field=models.IntegerField(verbose_name='Buto plotas'),
        ),
    ]
