# Generated by Django 4.2.1 on 2023-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyventojas', '0002_alter_butas_flat_nr_alter_butas_size_kv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butas',
            name='size_kv',
            field=models.IntegerField(verbose_name='Buto plotas kv'),
        ),
    ]
