# Generated by Django 4.2.1 on 2023-07-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyventojas', '0003_alter_butas_size_kv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Islaidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(verbose_name='Lėšų panaudojimas:')),
                ('repairs_cost', models.FloatField(verbose_name='Išleista suma:')),
            ],
            options={
                'verbose_name': 'Išlaidos',
                'verbose_name_plural': 'Išlaidos',
            },
        ),
        migrations.CreateModel(
            name='Kaupiamsis_Inasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Inaso suma')),
                ('date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyventojas.butas')),
            ],
            options={
                'verbose_name': 'Kaupiamsis inasas',
                'verbose_name_plural': 'Kaupiamieji Inasai',
            },
        ),
    ]
