# Generated by Django 4.2.1 on 2023-08-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracija', '0001_initial'),
        ('gyventojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaupiamsis_inasas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyventojas.flat'),
        ),
    ]
